### ISSUE TITLE
Missing npm package

### ISSUE THREAD

**Issue by kleonang** [halfwhole/luminus-downloader#7]
Hi, just tried out this luminus-downloader (good stuff btw). I noticed that I was missing the `yargs` package even after `npm install`. This was solved by running an additional command in terminal to install it: `npm i yargs`. Maybe it would be good to add this to README.md under the "Running the script" section in case others encounter this issue? Cheers!

**Comment by halfwhole** [comment]
Hi @kleonang! I've tried cloning the project and setting it up from scratch, but it doesn't seem like I can reproduce the issue unfortunately, running `npm install` does install `yargs@15.4.1` for me with no issues. I'm not sure why it happened :/
If the issue persists for you, I could surely add an extra note to the README if others face the same issue.

**Comment by kleonang** [comment]
I see, perhaps it is an issue specific to my system. I'm on macOS 11.5.2 for reference, in case others report the same issue. Anyways great job on the luminus downloader, look forward to using it for this semester and beyond! :)
